# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: c
install:
  - cp scripts/travis-tool.sh fakepackage
  - sudo -E fakepackage/travis-tool.sh bootstrap
  - fakepackage/travis-tool.sh bootstrap_devtools

script: ./travis-tool.sh run_tests

before_script:
  - cd fakepackage
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
