# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

# language: c
language: objective-c

env:
  global:
    - R_BUILD_ARGS=" "
  matrix:
    - BOOTSTRAP_OPTS=""
    - BOOTSTRAP_OPTS="--latex"
script:
  - which kpsewhich || true
  - which pdflatex || true
  - ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - df || true
  - df -h || true
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - ./travis-tool.sh bootstrap ${BOOTSTRAP_OPTS}
before_script:
  - ./travis-tool.sh dump_sysinfo
after_success:
  - ./travis-tool.sh dump_logs_by_extension out
after_failure:
  - ./travis-tool.sh dump_logs
install:
  - PATH=/usr/texbin:$PATH
  - ls -s /usr/texbin || true
  - which kpsewhich || true
  - which pdflatex || true
  - echo $PATH
  - cat ~/.bash_profile || true
  - cat ~/.bash_login || true
  - cat ~/.profile || true
  - cat /etc/profile || true
  - cat /etc/bash.bashrc || true
  - ./travis-tool.sh install_deps
  # TESTS
  # Test r_install (which accepts multiple arguments).
  - ./travis-tool.sh r_install stringr lubridate
  - Rscript -e 'library(stringr); library(lubridate)'
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh dump_sysinfo | egrep "^R version [0-9]+\.[0-9]+\.[0-9]+"
  # Test --latex option: pdflatex, kpsewhich
  - if test "${BOOTSTRAP_OPTS/--latex/}" != "${BOOTSTRAP_OPTS}"; then test -n "$(which kpsewhich)"; fi
  - if test "${BOOTSTRAP_OPTS/--latex/}" != "${BOOTSTRAP_OPTS}"; then test -n "$(which pdflatex)"; fi
  # Test without --latex option: no pdflatex, no kpsewhich
  - if test "${BOOTSTRAP_OPTS/--latex/}" = "${BOOTSTRAP_OPTS}"; then test -z "$(which kpsewhich)"; fi
  - if test "${BOOTSTRAP_OPTS/--latex/}" = "${BOOTSTRAP_OPTS}"; then test -z "$(which pdflatex)"; fi
