# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: c
# language: objective-c

env:
  matrix:
    - BOOTSTRAP_LATEX=" "
    - R_BUILD_ARGS=" " R_CHECK_ARGS="--as-cran" BOOTSTRAP_LATEX="1"
script: RunTests
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - source ./travis-tool.sh bootstrap
before_script:
  - DumpSysinfo
after_success:
  - DumpLogsByExtension out
after_failure:
  - DumpLogs
install:
  - InstallDeps
  # TESTS
  #
  # The following lines exist to test various features of our travis
  # scripts; don't use these as a model for other `.travis.yml` files.
  # Test aptget_install with multiple arguments.
  - if test ${OS} = Linux; then test -z "$(which tmux)"; fi
  - if test ${OS} = Linux; then test -z "$(which sponge)"; fi
  - if test ${OS} = Linux; then ./travis-tool.sh aptget_install tmux moreutils; fi
  - if test ${OS} = Linux; then test -n "$(which tmux)"; fi
  - if test ${OS} = Linux; then test -n "$(which sponge)"; fi
  # Test r_install (which accepts multiple arguments).
  - RInstall stringr lubridate
  - Rscript -e 'library(stringr); library(lubridate)'
  # Test github package installation.
  - Rscript -e 'stopifnot(!any(c("assertthat", "testthat") %in% installed.packages())'
  - GithubPackage assertthat
  - GithubPackage testthat
  - Rscript -e 'library(assertthat); library(testthat)'
  # Test R binary installation.
  - if test ${OS} = Linux; then RBinaryInstall RUnit survey; fi
  - if test ${OS} = Linux; then Rscript -e 'library(RUnit); library(survey)'; fi
  - DumpSysinfo | grep -q 'R version '
