# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: c
# language: objective-c

script:
  - Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="'"${CRAN}"'")); devtools:::install()'
  - Rscript tests/test-all.R
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
  # TODO(craigcitro): This line is nonsense; it's just used to test
  # that apt package installation works, since tmux is tiny and has no
  # dependencies. ;) Once we have a binary CRAN repo set up by default,
  # switch this to something more relevant.
  - ./travis-tool.sh aptget_install tmux
  # Test r_install (which accepts multiple arguments).
  - ./travis-tool.sh r_install stringr lubridate
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
