# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

language: c
# language: objective-c

env:
  global:
    - R_BUILD_ARGS=" "
  matrix:
    - BOOTSTRAP_OPTS=""
    - BOOTSTRAP_OPTS="--latex"
script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - ./travis-tool.sh bootstrap ${BOOTSTRAP_OPTS}
before_script:
  - ./travis-tool.sh dump_sysinfo
after_success:
  - ./travis-tool.sh dump_logs_by_extension out
after_failure:
  - ./travis-tool.sh dump_logs
install:
  - ./travis-tool.sh install_deps
  # TESTS
  #
  # The following lines exist to test various features of our travis
  # scripts; don't use these as a model for other `.travis.yml` files.
  # Test aptget_install with multiple arguments.
  - ./travis-tool.sh aptget_install tmux psmisc
  # Test r_install (which accepts multiple arguments).
  - ./travis-tool.sh r_install stringr lubridate
  - Rscript -e 'library(stringr); library(lubridate)'
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh r_binary_install RUnit survey
  - Rscript -e 'library(RUnit); library(survey)'
  - ./travis-tool.sh dump_sysinfo | egrep "^R version [0-9]+\.[0-9]+\.[0-9]+"
  # Test --latex option: both asymptote and pdflatex are installed
  - if test ${BOOTSTRAP_OPTS/--latex/} != ${BOOTSTRAP_OPTS}; then test -n "$(which asymptote)"; fi
  - if test ${BOOTSTRAP_OPTS/--latex/} != ${BOOTSTRAP_OPTS}; then test -n "$(which pdflatex)"; fi
  # Test without --latex option: only pdflatex is installed
  - if test ${BOOTSTRAP_OPTS/--latex/} = ${BOOTSTRAP_OPTS}; then test -z "$(which asymptote)"; fi
  - if test ${BOOTSTRAP_OPTS/--latex/} = ${BOOTSTRAP_OPTS}; then test -n "$(which pdflatex)"; fi
